// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDYOR0wbUcgw5Kvc7rXJjnullT75yYoZM',
    appId: '1:524034601081:web:97a359a76086bad83124a8',
    messagingSenderId: '524034601081',
    projectId: 'foodgram-d6ef7',
    authDomain: 'foodgram-d6ef7.firebaseapp.com',
    storageBucket: 'foodgram-d6ef7.firebasestorage.app',
    measurementId: 'G-F9GMH381JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFUq2Ah4Epo18-7EjsUX6O0Se0fEmsqU',
    appId: '1:524034601081:android:0aad8ca6811de46e3124a8',
    messagingSenderId: '524034601081',
    projectId: 'foodgram-d6ef7',
    storageBucket: 'foodgram-d6ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpOpO0lJH9NdQ5yTJTBQv7jlT4-VeBqA',
    appId: '1:524034601081:ios:b90718d07952b8e53124a8',
    messagingSenderId: '524034601081',
    projectId: 'foodgram-d6ef7',
    storageBucket: 'foodgram-d6ef7.firebasestorage.app',
    iosBundleId: 'com.example.foodgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpOpO0lJH9NdQ5yTJTBQv7jlT4-VeBqA',
    appId: '1:524034601081:ios:b90718d07952b8e53124a8',
    messagingSenderId: '524034601081',
    projectId: 'foodgram-d6ef7',
    storageBucket: 'foodgram-d6ef7.firebasestorage.app',
    iosBundleId: 'com.example.foodgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDYOR0wbUcgw5Kvc7rXJjnullT75yYoZM',
    appId: '1:524034601081:web:ae6c142a6612b4c03124a8',
    messagingSenderId: '524034601081',
    projectId: 'foodgram-d6ef7',
    authDomain: 'foodgram-d6ef7.firebaseapp.com',
    storageBucket: 'foodgram-d6ef7.firebasestorage.app',
    measurementId: 'G-DLLVVZ0DVC',
  );
}
